version: '3'
services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/train_model.py
    volumes:
      - app-vol:/app/voldata

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.front:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - app-vol:/app/voldata
    depends_on:
      - train

volumes:
  app-vol:
