name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd src
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Install DVC
      run: |
        source src/.venv/bin/activate
        pip install dvc[all]

    - name: Configure DVC
      run: |
        dvc remote modify myremote --local access_key_id ${{ secrets.YC_ACCESS_KEY_ID }}
        dvc remote modify myremote --local secret_access_key ${{ secrets.YC_SECRET_ACCESS_KEY }}

    - name: Pull data with DVC
      run: |
        source src/.venv/bin/activate
        dvc pull

    - name: Run unit tests and data quality tests
      run: |
        source src/.venv/bin/activate
        pip install pytest
        pytest tests/

    - name: Build Docker image
      run: |
        docker build -t vskolegov/mlops_final:${{ github.sha }} .
        docker tag vskolegov/mlops_final:${{ github.sha }} vskolegov/mlops_final:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker push vskolegov/mlops_final:${{ github.sha }}
        docker push vskolegov/mlops_final:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy Docker image
      run: |
        docker pull vskolegov/mlops_final:latest
        docker run -d -p 8000:8000 vskolegov/mlops_final:latest
